version: '2'
services:
  dev:
    container_name: nestjs_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27018:27018
    networks:
      - nesjs-network
    restart: always

networks:
    nesjs-network:
      driver: bridge