version: '2'
services:
  dev:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3456:3456
    networks:
      - restaurant-network
    depends_on:
      - mongodb
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    image : mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=restaurant
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - restaurant-network
    restart: always

networks:
    restaurant-network:
      driver: bridge